import { ChatMessage, Memory, Person, GeneratedFileSummary, UserProfile } from '../types';
import { apiFetch, getApiUrl, isCapacitorNative, MkuuApiError } from './apiConfig';
import { sendNativeSms } from './smsService';

const GEMINI_API_KEY_STORAGE = 'mkuu_gemini_api_key_v1';
export function getStoredGeminiApiKey(): string { if (typeof window === 'undefined') return ''; return localStorage.getItem(GEMINI_API_KEY_STORAGE) || ''; }
export function setStoredGeminiApiKey(key: string): void { if (typeof window === 'undefined') return; if (!key || !key.trim()) localStorage.removeItem(GEMINI_API_KEY_STORAGE); else localStorage.setItem(GEMINI_API_KEY_STORAGE, key.trim()); }
export interface ChatEngineParams { userId:string; message:string; conversationId:string; conversationHistory?:ChatMessage[]; isVoice?:boolean; attachments?:any[]; user?:UserProfile|null; memories?:Memory[]; people?:Person[]; signal?:AbortSignal; }
export interface ChatEngineResult { reply:string; cleanSpeechText:string; memoriesExtracted?:Memory[]; peopleRecognized?:Person[]; generatedFiles?:GeneratedFileSummary[]; engineUsed:'server'|'direct_gemini'; aiProvider?:string; chatModel?:string; intent?:string; }

export function cancelMkuuChat(): void {}
function normalizePhone(value:string){return String(value||'').replace(/[^+\d]/g,'');}
async function handleDirectSmsCommand(params:ChatEngineParams):Promise<ChatEngineResult|null>{
 const text=String(params.message||'').trim();
 if(!/\b(mtumie|tuma\s+sms|tuma\s+ujumbe|send\s+(?:an\s+)?sms)\b/i.test(text)) return null;
 const match=text.match(/(?:mkuu\s*[,;:]?\s*)?(?:mtumie|tuma\s+sms\s+(?:kwa\s+)?|tuma\s+ujumbe\s+(?:kwa\s+)?|send\s+(?:an\s+)?sms\s+(?:to\s+)?)\s+(.+?)(?:\s+sms\s*)?\s*[:\-]\s*(.+)$/i);
 if(!match)return null;
 const target=match[1].trim(); const message=match[2].trim(); const people=params.people||[]; const targetDigits=normalizePhone(target);
 const person=people.find(p=>normalizePhone(p.phone||'')===targetDigits||p.name.toLowerCase()===target.toLowerCase()||p.nickname?.toLowerCase()===target.toLowerCase());
 const to=normalizePhone(person?.phone||target);
 if(!/^\+?\d{7,15}$/.test(to)) return {reply:`Sijaweza kupata namba ya ${target}. Tafadhali weka mtu huyo kwenye Watu Wangu au tumia namba kamili.`,cleanSpeechText:`Sijaweza kupata namba ya ${target}.`,engineUsed:'server',intent:'sms_send_failed'};
 if(!isCapacitorNative()) return {reply:'Kutuma SMS moja kwa moja kunahitaji APK ya MKUU yenye SIM na ruhusa ya SMS.',cleanSpeechText:'Kutuma SMS moja kwa moja kunahitaji APK ya MKUU.',engineUsed:'server',intent:'sms_send_unavailable'};
 try{await sendNativeSms(to,message);return{reply:`Nimetuma SMS kwa ${person?.name||to}.`,cleanSpeechText:`Nimetuma SMS kwa ${person?.name||to}.`,engineUsed:'server',aiProvider:'Android SIM',intent:'sms_send'};}catch(e:any){return{reply:`SMS haikutumwa kwa ${person?.name||to}. ${e?.message||'Hakikisha ruhusa ya SMS na SIM ziko tayari.'}`,cleanSpeechText:'SMS haikutumwa.',engineUsed:'server',aiProvider:'Android SIM',intent:'sms_send_failed'};}
}

let streamPreview='';
function emitStream(text:string,done=false){if(typeof window==='undefined')return;streamPreview+=text;let node=document.getElementById('mkuu-stream-preview');if(!node&&!done){node=document.createElement('div');node.id='mkuu-stream-preview';node.setAttribute('aria-live','polite');Object.assign(node.style,{position:'fixed',left:'16px',right:'16px',bottom:'88px',zIndex:'9999',maxWidth:'760px',margin:'0 auto',padding:'14px 16px',borderRadius:'16px',background:'rgba(8,8,8,.96)',color:'#F5F2ED',border:'1px solid rgba(212,175,55,.45)',boxShadow:'0 18px 50px rgba(0,0,0,.45)',fontSize:'14px',lineHeight:'1.55',whiteSpace:'pre-wrap',maxHeight:'38vh',overflow:'auto',backdropFilter:'blur(14px)'});document.body.appendChild(node);}if(node)node.textContent=streamPreview;if(done){window.setTimeout(()=>document.getElementById('mkuu-stream-preview')?.remove(),120);streamPreview='';}}
function needsArtifactRoute(params:ChatEngineParams){const text=String(params.message||'').toLowerCase();const hasImage=(params.attachments||[]).some((a:any)=>String(a?.mimeType||'').startsWith('image/'));return hasImage||/\b(pdf|docx?|word|excel|xlsx|csv|logo|banner|poster|cartoon|picha|image|background|document|proposal|ripoti)\b/i.test(text);}
function needsImageRoute(params:ChatEngineParams){const text=String(params.message||'').toLowerCase();const hasImage=(params.attachments||[]).some((a:any)=>String(a?.mimeType||'').startsWith('image/'));const words=['picha','image','photo','logo','background','remove background','ondoa background','toa background','futa background','edit picha','hariri picha','hariri','edit image','tengeneza logo','tengeneza picha','generate image','create image','create logo','poster','banner','cartoon','transparent','png','2k','4k','hd','enhance','boresha'];return hasImage||words.some(w=>text.includes(w));}
function needsLiveSearch(message:string){const lower=String(message||'').toLowerCase();const patterns=[/\bwaziri mkuu\b/,/\brais wa\b/,/\bmakamu wa rais\b/,/\bkiongozi wa sasa\b/,/\bmkuu wa nchi\b/,/\bmkuu wa serikali\b/,/\bmeya wa\b/,/\bnaibu\s+waziri\b/,/\bwaziri wa\b/,/\bserikali ya sasa\b/,/\bcurrent\b/,/\blatest\b/,/\bsasa\b/,/\bwa sasa\b/,/\bleo\b/,/\bhivi punde\b/,/\bhabari mpya\b/,/\bhabari za leo\b/,/\bbei ya\b/,/\bthamani ya\b/,/\bexchange rate\b/,/\brate ya\b/,/\bmatokeo ya\b/,/\bratiba ya\b/,/\bmsimamo wa\b/,/\bnani ameshinda\b/,/\bnani kashinda\b/,/\bwho is\b/,/\bwho won\b/,/\btoday\b/,/\btonight\b/,/\bthis week\b/,/\bthis month\b/,/\b2025\b/,/\b2026\b/,/\bhabari\b/,/\bnews\b/,/\bmechi\b/,/\bmchezo\b/,/\banacheza\b/,/\bfixture\b/,/\bsports?\b/,/\bsoka\b/,/\bfootball\b/,/\byanga\b/,/\bsimba\b/,/\bazam\b/,/\bpamba\s+jiji\b/,/\bcoastal\s+union\b/,/\bjkt\s+tanzania\b/];return patterns.some(p=>p.test(lower));}
async function callImageStudio(params:ChatEngineParams):Promise<ChatEngineResult>{const attachments=params.attachments||[];const imageAttachment=attachments.find((a:any)=>String(a?.mimeType||'').startsWith('image/'));const imageBase64=imageAttachment?.base64Data||'';const mimeType=imageAttachment?.mimeType||'image/jpeg';const lower=String(params.message||'').toLowerCase();const isGeneration=!imageAttachment;const endpoint=isGeneration?'/api/image/generate':'/api/image/edit';const response=await apiFetch<any>(endpoint,{method:'POST',signal:params.signal,body:JSON.stringify({prompt:params.message,imageBase64:imageBase64||undefined,mimeType,filename:isGeneration?(lower.includes('logo')?'Logo_ya_Mkuu.png':'Picha_ya_Mkuu.png'):'Picha_Iliyohaririwa_Mkuu.png'})});if(!response?.success||!response?.file)throw new MkuuApiError({code:'IMAGE_GENERATION_FAILED',status:500,userMessage:'IMAGE STUDIO IMESHINDWA KUTENGENEZA PICHA\nTafadhali jaribu tena.',technicalDetails:'Image Studio returned no generated file',targetUrl:getApiUrl(endpoint)});const file={...response.file,downloadUrl:response.file.downloadUrl?.startsWith('http')||response.file.downloadUrl?.startsWith('data:')?response.file.downloadUrl:getApiUrl(response.file.downloadUrl)};return{reply:response.reply||'Picha yako imetengenezwa na MKUU Image Studio na iko tayari hapa chini.',cleanSpeechText:(response.reply||'Picha yako imetengenezwa na MKUU Image Studio.').replace(/[#*`_~[\]()]/g,' ').replace(/\s+/g,' ').trim(),generatedFiles:[file],engineUsed:'server',aiProvider:response.aiProvider||'Puter Image Studio',chatModel:response.modelUsed||'gemini-3.1-flash-image-preview',intent:isGeneration?'image_generation':'image_edit'};}
async function callDirectGemini(apiKey:string,params:ChatEngineParams):Promise<ChatEngineResult>{if(needsLiveSearch(params.message))return callNativeServerChat(params);const peopleText=(params.people||[]).slice(0,20).map(p=>`- ${p.name}${p.nickname?` (${p.nickname})`:''}: ${p.relationship}; ${p.phone||''}; ${p.notes||''}`).join('\n');const systemPrompt=`Wewe ni MKUU AI, msaidizi wa Max. Zungumza kwa Kiswahili fasaha. Tumia taarifa hizi za watu wa karibu inapohitajika:\n${peopleText||'Hakuna watu wa karibu waliosajiliwa.'}`;const rawHistory=Array.isArray(params.conversationHistory)?params.conversationHistory.slice(-10):[];const contents:any[]=rawHistory.filter(h=>h.content||h.attachments?.length).map(h=>({role:h.role==='user'?'user':'model',parts:[{text:h.content||''}]}));contents.push({role:'user',parts:[{text:params.message}]});const url=`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.7-flash:generateContent?key=${apiKey}`;const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:systemPrompt}]},contents,generationConfig:{temperature:0.7,maxOutputTokens:1024}}),signal:params.signal});if(!response.ok)throw new MkuuApiError({code:'GEMINI_UNAVAILABLE',status:response.status,userMessage:'GEMINI HAIPATIKANI KWA SASA\nTafadhali jaribu tena.',technicalDetails:`Gemini API error (${response.status})`,targetUrl:url});const data=await response.json();const rawText=data.candidates?.[0]?.content?.parts?.map((p:any)=>p?.text||'').join('')||'';if(!rawText.trim())throw new Error('Gemini returned an empty response');return{reply:rawText,cleanSpeechText:rawText.replace(/[#*`_~[\]()]/g,' ').replace(/\s+/g,' ').trim(),engineUsed:'direct_gemini',aiProvider:'Google Gemini',chatModel:'gemini-3.7-flash',intent:'chat'};}
async function callNativeServerChat(params:ChatEngineParams):Promise<ChatEngineResult>{const serverRes=await apiFetch<any>('/api/chat',{method:'POST',signal:params.signal,body:JSON.stringify({conversationId:params.conversationId,message:params.message,isVoice:params.isVoice,attachments:params.attachments||[],conversationHistory:(params.conversationHistory||[]).slice(-10),people:params.people||[]})});if(!serverRes?.reply)throw new MkuuApiError({code:'BACKEND_UNREACHABLE',userMessage:'SEVA YA MKUU HAIPATANI\nTafadhali jaribu tena.',technicalDetails:'Native Android chat returned an empty response payload',targetUrl:getApiUrl('/api/chat')});return{reply:serverRes.reply,cleanSpeechText:serverRes.cleanSpeechText||serverRes.reply,memoriesExtracted:serverRes.memoriesExtracted,peopleRecognized:serverRes.peopleRecognized,generatedFiles:serverRes.generatedFiles,engineUsed:'server',aiProvider:serverRes.aiProvider||'Exa',chatModel:serverRes.chatModel||'exa-live-search',intent:serverRes.intent||'chat'};}
async function streamServerChat(params:ChatEngineParams):Promise<ChatEngineResult>{return callNativeServerChat(params);}
export async function executeMkuuChat(params:ChatEngineParams):Promise<ChatEngineResult>{const smsCommand=await handleDirectSmsCommand(params);if(smsCommand)return smsCommand;if(needsImageRoute(params))return callImageStudio(params);if(needsLiveSearch(params.message))return callNativeServerChat(params);const directApiKey=getStoredGeminiApiKey();if(directApiKey&&directApiKey.trim().length>10)return callDirectGemini(directApiKey.trim(),params);if(isCapacitorNative())return callNativeServerChat(params);if(needsArtifactRoute(params)){const serverRes=await apiFetch<any>('/api/agent',{method:'POST',signal:params.signal,body:JSON.stringify({conversationId:params.conversationId,message:params.message,isVoice:params.isVoice,attachments:params.attachments,conversationHistory:(params.conversationHistory||[]).slice(-10),people:params.people||[]})});if(serverRes&&(serverRes.reply||serverRes.success))return{reply:serverRes.reply||'',cleanSpeechText:serverRes.cleanSpeechText||serverRes.reply||'',memoriesExtracted:serverRes.memoriesExtracted,peopleRecognized:serverRes.peopleRecognized,generatedFiles:serverRes.generatedFiles,engineUsed:'server',aiProvider:serverRes.aiProvider||'Google Gemini',chatModel:serverRes.chatModel||'gemini-3.7-flash',intent:serverRes.intent};throw new MkuuApiError({code:'BACKEND_UNREACHABLE',userMessage:'SEVA YA MKUU HAIPATANI\nTafadhali jaribu tena.',technicalDetails:'Empty Universal Agent response payload',targetUrl:'/api/agent'});}return streamServerChat(params);}
