import React, { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../services/apiConfig';
import { CheckCircle2, Clock3, Plus, CalendarDays, Bell, Users, Settings2, Smartphone, Zap, LayoutDashboard, Trash2 } from 'lucide-react';

type Task={id:string;title:string;notes?:string;dueAt?:string;priority:string;status:string};
type Event={id:string;title:string;startsAt:string;endsAt?:string;location?:string;notes?:string};
type Reminder={id:string;title:string;remindAt:string;repeat:string;enabled:boolean};
type Settings={language:string;notifications:boolean;quietHours:{enabled:boolean;start:string;end:string};proactiveAssistant:boolean;defaultTaskPriority:string;voiceActions:boolean;androidActions:boolean};

const isoFromLocal=(value:string)=>value?new Date(value).toISOString():undefined;
export const AssistantManager:React.FC=()=>{
 const [snapshot,setSnapshot]=useState<any>(null); const [section,setSection]=useState<'dashboard'|'tasks'|'calendar'|'reminders'|'people'|'proactive'|'android'|'settings'>('dashboard'); const [busy,setBusy]=useState(false);
 const load=async()=>{try{setSnapshot(await apiFetch<any>('/api/manager'));}catch(e){console.warn('Assistant Manager unavailable',e);}};
 useEffect(()=>{load(); const t=setInterval(load,30000); return()=>clearInterval(t);},[]);
 const tasks:Task[]=snapshot?.tasks||[]; const events:Event[]=snapshot?.events||[]; const reminders:Reminder[]=snapshot?.reminders||[]; const settings:Settings=snapshot?.settings||{language:'Kiswahili',notifications:true,quietHours:{enabled:false,start:'22:00',end:'07:00'},proactiveAssistant:true,defaultTaskPriority:'medium',voiceActions:true,androidActions:true};
 const [taskTitle,setTaskTitle]=useState(''); const [taskDue,setTaskDue]=useState(''); const [eventTitle,setEventTitle]=useState(''); const [eventStart,setEventStart]=useState(''); const [remTitle,setRemTitle]=useState(''); const [remAt,setRemAt]=useState('');
 const create=async(endpoint:string,body:any)=>{setBusy(true);try{await apiFetch(endpoint,{method:'POST',body:JSON.stringify(body)});await load();}finally{setBusy(false);}};
 const complete=async(id:string)=>{await apiFetch(`/api/manager/tasks/${id}`,{method:'PATCH',body:JSON.stringify({status:'done'})});load();};
 const remove=async(endpoint:string)=>{await apiFetch(endpoint,{method:'DELETE'});load();};
 const toggleSetting=async(key:keyof Settings,value:any)=>{await apiFetch('/api/manager/settings',{method:'PUT',body:JSON.stringify({[key]:value})});load();};
 const nav=[['dashboard','Dashboard',LayoutDashboard],['tasks','Kazi',CheckCircle2],['calendar','Kalenda',CalendarDays],['reminders','Vikumbusho',Bell],['people','Watu',Users],['proactive','Proactive AI',Zap],['android','Android Actions',Smartphone],['settings','Settings',Settings2]] as const;
 const upcoming=useMemo(()=>events.slice(0,5),[events]);
 return <div className="h-full overflow-y-auto p-4 md:p-6 bg-[#07090e] text-slate-100">
  <div className="max-w-6xl mx-auto space-y-5">
   <div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.25em] text-[#D4AF37]">MKUU AI</p><h2 className="text-2xl font-bold">Assistant Manager</h2><p className="text-sm text-slate-400">Kazi, kalenda, vikumbusho, watu, vitendo na uangalizi wa akili.</p></div><div className="flex gap-2 flex-wrap">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`px-3 py-2 rounded-lg text-xs border ${section===id?'bg-[#D4AF37]/15 border-[#D4AF37]/40 text-[#D4AF37]':'bg-white/[0.03] border-white/10 text-slate-300'}`}><Icon className="w-3.5 h-3.5 inline mr-1"/>{label}</button>)}</div></div>
   {section==='dashboard'&&<>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Kazi wazi',snapshot?.stats?.openTasks||0],['Zilizokamilika',snapshot?.stats?.completedTasks||0],['Matukio',snapshot?.stats?.upcomingEvents||0],['Vikumbusho',snapshot?.stats?.dueReminders||0]].map(([a,b])=><div key={String(a)} className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="text-xs text-slate-400">{a}</div><div className="text-2xl font-bold mt-1">{b}</div></div>)}</div>
    <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold mb-3">Kazi zinazosubiri</h3>{tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').slice(0,6).map(t=><div key={t.id} className="flex items-center justify-between py-2 border-b border-white/5"><span className="text-sm">{t.title}</span><button onClick={()=>complete(t.id)} className="text-emerald-400"><CheckCircle2 className="w-4 h-4"/></button></div>)}{!tasks.length&&<p className="text-sm text-slate-500">Hakuna kazi bado.</p>}</div><div className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold mb-3">Agenda ijayo</h3>{upcoming.map(e=><div key={e.id} className="py-2 border-b border-white/5"><div className="text-sm font-medium">{e.title}</div><div className="text-xs text-slate-400">{new Date(e.startsAt).toLocaleString('sw-TZ')}</div></div>)}{!upcoming.length&&<p className="text-sm text-slate-500">Hakuna tukio lililopangwa.</p>}</div></div>
   </>}
   {section==='tasks'&&<Panel title="Task & To-Do Manager"><div className="grid md:grid-cols-3 gap-2 mb-4"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Jina la kazi" className="md:col-span-2 rounded-lg bg-white text-slate-900 px-3 py-2 text-sm"/><input type="datetime-local" value={taskDue} onChange={e=>setTaskDue(e.target.value)} className="rounded-lg bg-white text-slate-900 px-3 py-2 text-sm"/><button disabled={!taskTitle||busy} onClick={()=>{create('/api/manager/tasks',{title:taskTitle,dueAt:isoFromLocal(taskDue),priority:settings.defaultTaskPriority});setTaskTitle('');setTaskDue('');}} className="rounded-lg bg-[#D4AF37] text-black px-3 py-2 text-sm font-bold"><Plus className="w-4 h-4 inline"/> Ongeza</button></div>{tasks.map(t=><Row key={t.id} title={t.title} meta={`${t.priority}${t.dueAt?' • '+new Date(t.dueAt).toLocaleString('sw-TZ'):''}`} done={t.status==='done'} onDone={()=>complete(t.id)} onDelete={()=>remove(`/api/manager/tasks/${t.id}`)}/>)}</Panel>}
   {section==='calendar'&&<Panel title="Calendar & Schedule Manager"><div className="grid md:grid-cols-3 gap-2 mb-4"><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Jina la tukio" className="md:col-span-2 rounded-lg bg-white text-slate-900 px-3 py-2 text-sm"/><input type="datetime-local" value={eventStart} onChange={e=>setEventStart(e.target.value)} className="rounded-lg bg-white text-slate-900 px-3 py-2 text-sm"/><button disabled={!eventTitle||!eventStart} onClick={()=>{create('/api/manager/calendar',{title:eventTitle,startsAt:isoFromLocal(eventStart)});setEventTitle('');setEventStart('');}} className="rounded-lg bg-[#D4AF37] text-black px-3 py-2 text-sm font-bold"><Plus className="w-4 h-4 inline"/> Panga</button></div>{events.map(e=><Row key={e.id} title={e.title} meta={new Date(e.startsAt).toLocaleString('sw-TZ')+(e.location?' • '+e.location:'')} onDelete={()=>remove(`/api/manager/calendar/${e.id}`)}/>)}</Panel>}
   {section==='reminders'&&<Panel title="Smart Reminders"><div className="grid md:grid-cols-3 gap-2 mb-4"><input value={remTitle} onChange={e=>setRemTitle(e.target.value)} placeholder="Nikumbushe..." className="md:col-span-2 rounded-lg bg-white text-slate-900 px-3 py-2 text-sm"/><input type="datetime-local" value={remAt} onChange={e=>setRemAt(e.target.value)} className="rounded-lg bg-white text-slate-900 px-3 py-2 text-sm"/><button disabled={!remTitle||!remAt} onClick={()=>{create('/api/manager/reminders',{title:remTitle,remindAt:isoFromLocal(remAt),repeat:'none'});setRemTitle('');setRemAt('');}} className="rounded-lg bg-[#D4AF37] text-black px-3 py-2 text-sm font-bold"><Bell className="w-4 h-4 inline"/> Weka</button></div>{reminders.map(r=><Row key={r.id} title={r.title} meta={`${new Date(r.remindAt).toLocaleString('sw-TZ')} • ${r.repeat}`} onDelete={()=>remove(`/api/manager/reminders/${r.id}`)}/>)}</Panel>}
   {section==='people'&&<Panel title="People Manager"><p className="text-sm text-slate-300 mb-4">People Manager iliyopo imeunganishwa na Assistant Manager. MKUU anaweza kutumia watu waliopo kwa context ya tasks, reminders na mawasiliano.</p><div className="grid md:grid-cols-3 gap-3">{(snapshot?.people||[]).map((p:any)=><div key={p.id} className="rounded-lg border border-white/10 p-3"><div className="font-semibold">{p.name}</div><div className="text-xs text-slate-400">{p.relationship}</div><div className="text-xs mt-2">{p.phone||'Hakuna simu'}</div></div>)}<div className="rounded-lg border border-dashed border-white/10 p-3 text-sm text-slate-500">Watu wapya bado wanaongezwa kupitia Watu wa Karibu.</div></div></Panel>}
   {section==='proactive'&&<Panel title="Proactive Assistant"><div className="grid md:grid-cols-3 gap-3"><Toggle label="Proactive Assistant" value={settings.proactiveAssistant} onChange={v=>toggleSetting('proactiveAssistant',v)}/><Toggle label="Notifications" value={settings.notifications} onChange={v=>toggleSetting('notifications',v)}/><Toggle label="Quiet Hours" value={settings.quietHours.enabled} onChange={v=>toggleSetting('quietHours',{...settings.quietHours,enabled:v})}/></div><div className="mt-5 rounded-xl bg-emerald-500/10 border border-emerald-500/20 p-4 text-sm">MKUU atafuatilia kazi zilizo wazi, matukio yanayokuja na vikumbusho vilivyofika muda. UI hii hu-refresh kila sekunde 30.</div></Panel>}
   {section==='android'&&<Panel title="Android Actions"><div className="grid md:grid-cols-3 gap-3"><ActionCard icon={<Smartphone/>} title="Notifications" text="Ruhusu MKUU kutumia notifications za kifaa kwa reminders." enabled={settings.notifications} onClick={()=>toggleSetting('notifications',!settings.notifications)}/><ActionCard icon={<Clock3/>} title="Voice Actions" text="Voice commands zinaweza kuunda tasks, reminders na agenda kupitia chat." enabled={settings.voiceActions} onClick={()=>toggleSetting('voiceActions',!settings.voiceActions)}/><ActionCard icon={<Zap/>} title="Android Actions" text="Hifadhi intents za call, SMS, calendar na reminder kwa UI ya Android." enabled={settings.androidActions} onClick={()=>toggleSetting('androidActions',!settings.androidActions)}/></div></Panel>}
   {section==='settings'&&<Panel title="Assistant Settings"><div className="grid md:grid-cols-2 gap-3"><Select label="Lugha" value={settings.language} options={['Kiswahili','English','Auto']} onChange={v=>toggleSetting('language',v)}/><Select label="Default task priority" value={settings.defaultTaskPriority} options={['low','medium','high','urgent']} onChange={v=>toggleSetting('defaultTaskPriority',v)}/><Toggle label="Notifications" value={settings.notifications} onChange={v=>toggleSetting('notifications',v)}/><Toggle label="Proactive Assistant" value={settings.proactiveAssistant} onChange={v=>toggleSetting('proactiveAssistant',v)}/><Toggle label="Voice Actions" value={settings.voiceActions} onChange={v=>toggleSetting('voiceActions',v)}/><Toggle label="Android Actions" value={settings.androidActions} onChange={v=>toggleSetting('androidActions',v)}/></div></Panel>}
  </div>
 </div>;
};
const Panel:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><section className="rounded-xl border border-white/10 bg-white/[0.02] p-4"><h3 className="font-bold text-lg mb-4">{title}</h3>{children}</section>;
const Row:React.FC<{title:string;meta?:string;done?:boolean;onDone?:()=>void;onDelete:()=>void}>=({title,meta,done,onDone,onDelete})=><div className="flex items-center justify-between gap-3 py-3 border-b border-white/5"><div><div className={`text-sm ${done?'line-through text-slate-500':''}`}>{title}</div>{meta&&<div className="text-xs text-slate-500 mt-1">{meta}</div>}</div><div className="flex gap-2">{onDone&&<button onClick={onDone} className="text-emerald-400"><CheckCircle2 className="w-4 h-4"/></button>}<button onClick={onDelete} className="text-red-400"><Trash2 className="w-4 h-4"/></button></div></div>;
const Toggle:React.FC<{label:string;value:boolean;onChange:(v:boolean)=>void}>=({label,value,onChange})=><button onClick={()=>onChange(!value)} className="flex items-center justify-between rounded-lg border border-white/10 p-3 text-left"><span className="text-sm">{label}</span><span className={`w-10 h-5 rounded-full ${value?'bg-emerald-500':'bg-slate-700'} relative`}><span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition ${value?'left-5':'left-0.5'}`}/></span></button>;
const Select:React.FC<{label:string;value:string;options:string[];onChange:(v:string)=>void}>=({label,value,options,onChange})=><label className="rounded-lg border border-white/10 p-3 text-sm block">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full bg-[#111] border border-white/10 rounded px-2 py-2">{options.map(o=><option key={o}>{o}</option>)}</select></label>;
const ActionCard:React.FC<{icon:React.ReactNode;title:string;text:string;enabled:boolean;onClick:()=>void}>=({icon,title,text,enabled,onClick})=><button onClick={onClick} className="text-left rounded-xl border border-white/10 p-4 hover:border-[#D4AF37]/30"><div className="text-[#D4AF37] mb-2">{icon}</div><div className="font-semibold">{title}</div><div className="text-xs text-slate-400 mt-1">{text}</div><div className="text-xs mt-3 text-emerald-400">{enabled?'Imewezeshwa':'Imezimwa'}</div></button>;
export default AssistantManager;
